### ISSUE TITLE
Is there any method to create a ZKPK of signature？

### ISSUE THREAD

**Issue by WystanW** [gijsvl/camenisch-lysyanskaya#1]
Hi ！
I found that in **verify** function，the parameters constain the message m and the signature sigma. Is there any method to hide the  signature and the message which means create a ZKPK of the signature？

**Comment by gijsvl** [comment]
Hi, no, this was kind of a test project, and is not used anywhere in practice. I would also advice against using this code unless you do some serious work on it. I've never added the ZKPoK functionality for proving knowledge of a signature.
